GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Google me",
  "author": "SF",
  "url": "http://www.google.com",
  "likes": 0
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Sunlight",
  "author": "SF",
  "url": "http://www.sunlightx.com",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React patterns", 
  "author": "Michael Chan", 
  "url": "https://reactpatterns.com/", 
  "likes": 7
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "username",
  "name": "User Name",
  "password": "password",
  "blogs": []
}

// Login authentication
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

// Authenticated create
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwibmFtZSI6IlVzZXIgTmFtZSIsImlkIjoiNWYzNTZhYWQyMTc5NTQwYzM0YmVhNjI0IiwiaWF0IjoxNTk3MzQxNzUzfQ.mVoSRDVpn3Gt4fevKMKtXahEzF2PvwfFuhkIiEXt_lk

{
  "title": "React patterns", 
  "author": "Michael Chan", 
  "url": "https://reactpatterns.com/", 
  "likes": 7
}

// Authenticated delete
###
DELETE http://localhost:3003/api/blogs/5f35839b69412f09c0def5f5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwibmFtZSI6IlVzZXIgTmFtZSIsImlkIjoiNWYzNTZhYWQyMTc5NTQwYzM0YmVhNjI0IiwiaWF0IjoxNTk3MzQxNzUzfQ.mVoSRDVpn3Gt4fevKMKtXahEzF2PvwfFuhkIiEXt_lk
