GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Google me",
  "author": "SF",
  "url": "www.google.com",
  "likes": 0
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Sunlight",
  "author": "SF",
  "url": "www.sunlightx.com",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React patterns", 
  "author": "Michael Chan", 
  "url": "https://reactpatterns.com/", 
  "likes": 7
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "username",
  "name": "User Name",
  "password": "password",
  "blogs": []
}